org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.3.0
forge_version_range=[47,48)
loader_version_range=[47,48)
mapping_channel=official
mapping_version=1.20.1

## Mod
mod_id=jujutsukaisen
mod_name=Jujutsu Kaisen: Domain of the Strongest
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.jujutsukaisen
mod_authors=sad4830
mod_description=Jujutsu Kaisen for Forge 1.20.1 - Satoru Gojo, Ryomen Sukuna, Kinji Hakari and Mahoraga, with cursed energy, techniques and Domain Expansions.
